theme: jekyll-theme-cayman
title: Hi I'm Hoang!
description: Welcome to where I documented my thoughts (so that I do not forget them) on all things Bioengineering, Medical Innovations and Global Health from a college student's perspective.

